# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [34]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def find_det(multipliers):
    """
    The function calculates subtotals 
    in the amount equal to det
    """
    multipliers_sum = 0
    for x in multipliers:
        multipliers_sum += x
    return multipliers_sum


def subtotal(list_order):
    """The function generates multipliers use a order list """
    global a
    multipliers = []
    n = len(a)
    for order in list_order:
        invert = 0
        for p in range(n - 1):
            for q in range(p + 1, n): 
                if order[p] > order[q]:
                    invert += 1
        multiplier = 1 if invert % 2 == 0 else -1
        for k in range(n):
            multiplier *= a [k] [order[k]]
        else:
            multipliers.append(multiplier)
    return multipliers

def perm():
    """The function generates list of permutations"""
    global a
    n = len(a)
    return list(itertools.permutations([i for i in range(n)], n))

dim = input("Enter size of matrix: ")
while not dim.isnumeric():
    print("Error, this is not the case")
    dim = input("Enter again: ")
try:
    dim = int(dim)
    a = random_matrix(dim)
    det = find_det(subtotal(perm()))
    print(a)
    print("result: det(A) =", det)
except ValueError as fail:
    print(fail)






[[4 7 5]
 [9 0 0]
 [7 7 0]]
result: det(A) = 315
315.0
